name: assembly-env
channels:
  - bioconda
  - anaconda
  - r
  - defaults
  - conda-forge
dependencies:
  - blast
  - bamtools
  - flye
  - ragtag
  - gnuplot
  - java-jdk
  - minimap2
  - quast
  - samtools
  - simplejson
  - colormath
  - cryptography
  - libgcc
  - blas
  - boost
  - bzip2
  - curl
  - git 
  - glib
  - graphite2
  - libcurl
  - markdown
  - markupsafe
  - matplotlib
  - openjdk
  - sqlite
  - time 
  - hmmer 
  - wget
  - yaml
