name: assembly-env
channels:
  - bioconda
  - anaconda
  - r
  - defaults
  - conda-forge
dependencies:
  - blast
  - bamtools
  - flye
  - ragtag
  - glimmerhmm
  - gnuplot
  - java-jdk
  - libdeflate
  - minimap2
  - quast
  - samtools
  - simplejson
  - colormath
  - cryptography
  - libgcc
  - lzstring
  - pango
  - spectra
  - tk
  - asn1crypto
  - backports
  - backports.functools_lru_cache
  - backports_abc
  - blas
  - boost
  - bzip2
  - ca-certificates
  - cairo
  - certifi
  - cffi
  - chardet
  - click
  - curl
  - cycler
  - dbus
  - decorator
  - enum34
  - expat
  - font-ttf-dejavu-sans-mono
  - fontconfig
  - freetype
  - functools32
  - future
  - futures
  - git 
  - giflib
  - glib
  - graphite2
  - gst-plugins-base
  - gstreamer
  - harfbuzz
  - icu
  - idna
  - intel-openmp
  - ipaddress
  - jinja2
  - joblib
  - jpeg
  - kiwisolver
  - krb5
  - libboost
  - libcurl
  - libedit
  - libffi
  - libgcc-ng
  - libgd
  - libgfortran-ng
  - libpng
  - libssh2
  - libstdcxx-ng
  - libtiff
  - libuuid
  - libwebp
  - libxcb
  - libxml2
  - markdown
  - markupsafe
  - matplotlib
  - mkl
  - mkl_fft
  - mkl_random
  - ncurses
  - networkx
  - numpy
  - numpy-base
  - openjdk
  - openssl
  - pcre
  - perl
  - pip
  - pixman
  - py-boost
  - pycparser
  - pyopenssl
  - pyparsing
  - pyqt
  - pysocks
  - python-dateutil
  - pytz
  - pyyaml
  - qt
  - readline
  - requests
  - sqlite
  - subprocess32
  - tornado
  - urllib3
  - time 
  - hmmer 
  - wget
  - wheel
  - xz
  - yaml
  - zlib
  - zstd
